title: Sofian EL ATIFI
url: "https://sofianelatifi.github.io"
baseurl: ""
markdown: kramdown

kramdown:
  math_engine: katex

sass:
  style: compressed
  sass_dir: _sass

# Navigation: Ensure these files exist at the specified paths
nav:
  - name: "About"
    link: "/about"
  - name: "Research"
    link: "/research"
  - name: "Teaching"
    link: "/teaching"
  - name: "Contact"
    link: "/contact"
  - name: "CV"
    link: "/resume.pdf"
